// CraftMind Fishing — Expanded Species
// Additional species for the Sitka ecosystem. These merge into the
// main species registry in sitka-species.js via the integration function.

export const EXPANDED_SPECIES = [

  // ═══════════════════════════════════════════════════════════════
  // MORE GROUNDFISH / ROCKFISH
  // ═══════════════════════════════════════════════════════════════
  {
    id: 'pacific_ocean_perch', name: 'Pacific Ocean Perch', scientificName: 'Sebastes alutus',
    category: 'groundfish', emoji: '🐠', rarity: 'Common',
    description: 'The most commercially important rockfish. Schools in deep water. 2-4 lbs.',
    personality: 'The workhorse rockfish. Common, tasty, and everywhere offshore.',
    biomes: ['open_ocean', 'rocky_pinnacles'],
    preferredDepth: [30, 100], preferredSeason: ['summer', 'fall'], peakMonth: [7, 8],
    sizeRange: [1, 5], avgWeight: 2.5, fightStrength: 4, speed: 4,
    baseValue: 5, cookValue: 12, marketDemand: 'moderate',
    preferredBait: ['herring', 'squid'],
    schools: true, predators: ['halibut', 'lingcod'],
    notes: 'Big commercial trawl fishery. Not glamorous but a staple of SE Alaska.',
  },
  {
    id: 'copper_rockfish', name: 'Copper Rockfish', scientificName: 'Sebastes caurinus',
    category: 'groundfish', emoji: '🟤', rarity: 'Uncommon',
    description: 'Nearshore rockfish with beautiful copper coloring. 3-6 lbs.',
    personality: 'Copper-colored introvert. Stays near the kelp line.',
    biomes: ['kelp_forest', 'rocky_pinnacles'],
    preferredDepth: [3, 25], preferredSeason: ['summer'], peakMonth: [6, 7, 8],
    sizeRange: [1, 6], avgWeight: 3.5, fightStrength: 5, speed: 4,
    baseValue: 10, cookValue: 25, marketDemand: 'low',
    preferredBait: ['shrimp', 'small_jig'],
    schools: false, predators: ['lingcod'],
    notes: 'Pretty fish. Common nearshore for sport fishermen. Good eating.',
  },
  {
    id: 'redbanded_rockfish', name: 'Redbanded Rockfish', scientificName: 'Sebastes babcocki',
    category: 'groundfish', emoji: '🔴', rarity: 'Uncommon',
    description: 'Deep water rockfish with red bands. 3-5 lbs.',
    personality: 'Deep and colorful. You have to go down to find this one.',
    biomes: ['rocky_pinnacles', 'deep_trench'],
    preferredDepth: [40, 100], preferredSeason: ['fall', 'winter'], peakMonth: [9, 10],
    sizeRange: [2, 5], avgWeight: 3, fightStrength: 4, speed: 3,
    baseValue: 12, cookValue: 28, marketDemand: 'low',
    preferredBait: ['herring', 'squid'],
    schools: false, predators: ['halibut', 'sleeper_shark'],
    notes: 'Deep water rockfish. Part of the "miscellaneous rockfish" complex commercially.',
  },
  {
    id: 'widow_rockfish', name: 'Widow Rockfish', scientificName: 'Sebastes entomelas',
    category: 'groundfish', emoji: '🖤', rarity: 'Uncommon',
    description: 'Deep water, common bycatch in commercial fisheries.',
    personality: 'The widow. Dark-colored, deep-dwelling, often caught by accident.',
    biomes: ['open_ocean', 'deep_trench'],
    preferredDepth: [50, 150], preferredSeason: ['summer', 'fall'], peakMonth: [7, 8],
    sizeRange: [1, 4], avgWeight: 2.5, fightStrength: 3, speed: 3,
    baseValue: 6, cookValue: 14, marketDemand: 'low',
    preferredBait: ['squid', 'herring'],
    schools: true, predators: ['halibut'],
    notes: 'Common bycatch species. Not heavily targeted but part of the rockfish complex.',
  },
  {
    id: 'rougheye_rockfish', name: 'Rougheye Rockfish', scientificName: 'Sebastes aleutianus',
    category: 'groundfish', emoji: '👁️', rarity: 'Rare',
    description: 'DEEP water. Can live 150+ years — one of the longest-lived fish on Earth.',
    personality: 'Has seen things. Lived through three centuries of ocean. Respect it.',
    biomes: ['deep_trench'],
    preferredDepth: [80, 200], preferredSeason: ['year_round'], peakMonth: [3, 4],
    sizeRange: [2, 8], avgWeight: 4, fightStrength: 4, speed: 2,
    baseValue: 20, cookValue: 40, marketDemand: 'low',
    preferredBait: ['squid', 'herring'],
    schools: false, predators: ['sleeper_shark', 'sixgill_shark'],
    notes: '150+ years old. Longest-lived rockfish. Caught in deep water longline fisheries. Catch and release if possible — respect the elders.',
  },
  {
    id: 'shortspine_thornyhead', name: 'Shortspine Thornyhead', scientificName: 'Sebastolobus alascanus',
    category: 'groundfish', emoji: '🦔', rarity: 'Uncommon',
    description: 'Deep water, orange, looks like a rockfish with thorns. 2-4 lbs.',
    personality: 'Spiky and orange. The pineapple of the deep.',
    biomes: ['deep_trench', 'rocky_pinnacles'],
    preferredDepth: [60, 200], preferredSeason: ['fall', 'winter'], peakMonth: [10, 11],
    sizeRange: [1, 4], avgWeight: 2, fightStrength: 3, speed: 2,
    baseValue: 15, cookValue: 30, marketDemand: 'moderate',
    preferredBait: ['squid', 'herring'],
    schools: false, predators: ['sleeper_shark'],
    notes: 'Often called "idiot fish" by fishermen because of the blank stare. Actually excellent eating.',
  },
  {
    id: 'longspine_thornyhead', name: 'Longspine Thornyhead', scientificName: 'Sebastolobus altivelis',
    category: 'groundfish', emoji: '🦔', rarity: 'Uncommon',
    description: 'Similar to shortspine but with longer spines. Bycatch in sablefish fishery.',
    personality: 'Even spikier cousin. Shares the deep water with shortspine.',
    biomes: ['deep_trench'],
    preferredDepth: [100, 300], preferredSeason: ['winter'], peakMonth: [1, 2],
    sizeRange: [1, 3], avgWeight: 1.5, fightStrength: 2, speed: 2,
    baseValue: 12, cookValue: 25, marketDemand: 'low',
    preferredBait: ['squid'],
    schools: false, predators: ['sleeper_shark'],
    notes: 'Deeper than shortspine. Common bycatch in sablefish longline fishery.',
  },
  {
    id: 'rock_greenling', name: 'Rock Greenling', scientificName: 'Hexagrammos lagocephalus',
    category: 'groundfish', emoji: '🐟', rarity: 'Uncommon',
    description: 'Similar to kelp greenling but prefers rocky areas. Males are beautifully colored.',
    personality: 'The kelp greenling\'s rugged cousin. More rocks, less kelp.',
    biomes: ['rocky_pinnacles', 'tidal_flats'],
    preferredDepth: [1, 20], preferredSeason: ['summer'], peakMonth: [7, 8],
    sizeRange: [0.5, 4], avgWeight: 2, fightStrength: 3, speed: 4,
    baseValue: 5, cookValue: 12, marketDemand: 'low',
    preferredBait: ['shrimp', 'small_jig'],
    schools: false, predators: ['lingcod'],
    notes: 'Males get striking blue-green coloring during breeding. Often caught while rockfishing.',
  },

  // ═══════════════════════════════════════════════════════════════
  // MORE PELAGICS
  // ═══════════════════════════════════════════════════════════════
  {
    id: 'jack_mackerel', name: 'Jack Mackerel', scientificName: 'Trachurus symmetricus',
    category: 'pelagic', emoji: '🐟', rarity: 'Uncommon',
    description: 'Schooling pelagic fish. Offshore. Good bait for halibut.',
    personality: 'The offshore school bus. Where there\'s jack mackerel, bigger fish follow.',
    biomes: ['open_ocean'],
    preferredDepth: [5, 50], preferredSeason: ['summer', 'fall'], peakMonth: [8, 9],
    sizeRange: [0.5, 3], avgWeight: 1, fightStrength: 3, speed: 6,
    baseValue: 1, cookValue: 3, marketDemand: 'low',
    preferredBait: ['small_lure', 'sabiki'],
    schools: true, predators: ['salmon', 'tuna', 'halibut'],
    notes: 'Often caught on sabiki rigs offshore. Use them for halibut bait.',
  },
  {
    id: 'pacific_saury', name: 'Pacific Saury', scientificName: 'Cololabis saira',
    category: 'pelagic', emoji: '🐟', rarity: 'Uncommon',
    description: 'Needlefish-like, seasonal offshore visitor.',
    personality: 'The needle of the sea. Fast, skinny, and seasonal.',
    biomes: ['open_ocean'],
    preferredDepth: [1, 30], preferredSeason: ['fall'], peakMonth: [9, 10],
    sizeRange: [0.3, 1], avgWeight: 0.5, fightStrength: 2, speed: 7,
    baseValue: 2, cookValue: 5, marketDemand: 'low',
    preferredBait: ['small_lure'],
    schools: true, predators: ['salmon', 'tuna'],
    notes: 'Seasonal. Sometimes show up in large schools offshore. More common in Japan but visit Alaska.',
  },

  // ═══════════════════════════════════════════════════════════════
  // MORE FLATFISH
  // ═══════════════════════════════════════════════════════════════
  {
    id: 'pacific_sanddab', name: 'Pacific Sanddab', scientificName: 'Citharichthys sordidus',
    category: 'groundfish', emoji: '🐟', rarity: 'Common',
    description: 'Small flatfish, good eating, common on sandy bottom. "The hidden treasure."',
    personality: 'Flat and delicious. Hides on sandy bottom waiting to be sautéed.',
    biomes: ['sheltered_sound', 'tidal_flats', 'open_ocean'],
    preferredDepth: [5, 60], preferredSeason: ['summer', 'fall'], peakMonth: [7, 8, 9],
    sizeRange: [0.3, 2], avgWeight: 0.8, fightStrength: 2, speed: 2,
    baseValue: 6, cookValue: 18, marketDemand: 'moderate',
    preferredBait: ['shrimp', 'small_hook'],
    schools: false, predators: ['halibut', 'lingcod'],
    notes: 'Pan-fried sanddabs with lemon butter are a West Coast delicacy. Often overlooked by sport fishermen.',
  },
  {
    id: 'starry_flounder', name: 'Starry Flounder', scientificName: 'Platichthys stellatus',
    category: 'groundfish', emoji: '⭐', rarity: 'Common',
    description: 'Estuaries and shallow water. Starry pattern on top side. Common.',
    personality: 'The star-crossed flounder. Can live in both salt and fresh water.',
    biomes: ['river_estuary', 'tidal_flats', 'freshwater_river'],
    preferredDepth: [0, 15], preferredSeason: ['spring', 'summer', 'fall'], peakMonth: [5, 6, 7],
    sizeRange: [0.5, 6], avgWeight: 2, fightStrength: 3, speed: 3,
    baseValue: 4, cookValue: 12, marketDemand: 'low',
    preferredBait: ['shrimp', 'worm'],
    schools: false, predators: ['halibut', 'seal'],
    notes: 'Can tolerate brackish and fresh water. Often caught in estuaries. The star pattern on the eyed side is distinctive.',
  },
  {
    id: 'english_sole', name: 'English Sole', scientificName: 'Parophrys vetulus',
    category: 'groundfish', emoji: '🐟', rarity: 'Common',
    description: 'Sandy bottom flatfish. 1-3 lbs. Mild, sweet meat.',
    personality: 'The quiet flatfish. Sandy bottom, mild flavor, no drama.',
    biomes: ['sheltered_sound', 'tidal_flats'],
    preferredDepth: [5, 50], preferredSeason: ['summer', 'fall'], peakMonth: [7, 8],
    sizeRange: [0.5, 3], avgWeight: 1.5, fightStrength: 2, speed: 2,
    baseValue: 5, cookValue: 14, marketDemand: 'moderate',
    preferredBait: ['shrimp', 'clam'],
    schools: false, predators: ['halibut'],
    notes: 'Good eating but easily confused with other soles. Fish and chips potential.',
  },
  {
    id: 'petrale_sole', name: 'Petrale Sole', scientificName: 'Eopsetta jordani',
    category: 'groundfish', emoji: '🐟', rarity: 'Uncommon',
    description: 'Deeper flatfish, 2-5 lbs. Prized for its mild, sweet flesh.',
    personality: 'The fancy flatfish. Deeper, bigger, better-eating.',
    biomes: ['open_ocean', 'sheltered_sound'],
    preferredDepth: [15, 80], preferredSeason: ['summer', 'fall'], peakMonth: [8, 9],
    sizeRange: [1, 5], avgWeight: 2.5, fightStrength: 3, speed: 2,
    baseValue: 12, cookValue: 35, marketDemand: 'high',
    preferredBait: ['shrimp', 'squid'],
    schools: false, predators: ['halibut'],
    notes: 'The best-eating sole on the Pacific coast. Restaurant quality. Worth targeting.',
  },

  // ═══════════════════════════════════════════════════════════════
  // ADDITIONAL SHARKS
  // ═══════════════════════════════════════════════════════════════
  {
    id: 'blue_shark', name: 'Blue Shark', scientificName: 'Prionace glauca',
    category: 'shark', emoji: '🦈', rarity: 'Rare',
    description: 'Offshore pelagic shark. Beautiful blue coloration. 6-12 feet.',
    personality: 'Sleek and blue. The open ocean\'s most elegant predator.',
    biomes: ['open_ocean'],
    preferredDepth: [5, 100], preferredSeason: ['summer', 'fall'], peakMonth: [8, 9],
    sizeRange: [50, 300], avgWeight: 150, fightStrength: 8, speed: 9,
    baseValue: 0, cookValue: 0, marketDemand: 'sport_only',
    preferredBait: ['mackerel', 'squid'],
    schools: false, predators: ['orca'],
    notes: 'Beautiful blue shark. Offshore only. Catch and release. Sport fishing target.',
  },
  {
    id: 'great_white_shark', name: 'Great White Shark', scientificName: 'Carcharodon carcharias',
    category: 'shark', emoji: '🦈', rarity: 'Legendary',
    description: 'ULTRA RARE easter egg. They ARE in Alaska waters — confirmed by researchers. One caught in a salmon net in SE Alaska.',
    personality: 'The legend. If you see one, nobody will believe you.',
    biomes: ['open_ocean', 'deep_trench'],
    preferredDepth: [10, 200], preferredSeason: ['summer', 'fall'], peakMonth: [8, 9],
    sizeRange: [500, 4000], avgWeight: 2000, fightStrength: 10, speed: 8,
    baseValue: 0, cookValue: 0, marketDemand: 'none',
    preferredBait: ['none'],
    schools: false, predators: ['orca'],
    notes: 'ULTRA ULTRA RARE easter egg. Confirmed in Alaska waters but exceedingly rare. In 2023, one was caught in a salmon net near Ketchikan. If you encounter one… just watch.',
  },

  // ═══════════════════════════════════════════════════════════════
  // AMPHIBIANS & FRESHWATER
  // ═══════════════════════════════════════════════════════════════
  {
    id: 'rough_skinned_newt', name: 'Rough-skinned Newt', scientificName: 'Taricha granulosa',
    category: 'easter_egg', emoji: '🦎', rarity: 'Rare',
    description: 'Toxic! Found near streams. One of the most toxic animals on Earth. DO NOT TOUCH.',
    personality: 'Small, slow, and DEADLY. The cute one that kills. Tetrodotoxin.',
    biomes: ['freshwater_river', 'river_estuary'],
    preferredDepth: [0, 2], preferredSeason: ['spring', 'summer'], peakMonth: [5, 6],
    sizeRange: [0.05, 0.2], avgWeight: 0.1, fightStrength: 0, speed: 1,
    baseValue: 0, cookValue: 0, marketDemand: 'none',
    preferredBait: ['none'],
    schools: false, predators: ['garter_snake'],
    notes: 'Easter egg encounter. Contains tetrodotoxin (same as pufferfish). Can kill a human. In a biology lesson moment, the game explains coevolution with garter snakes.',
  },
  {
    id: 'red_legged_frog', name: 'Red-legged Frog', scientificName: 'Rana aurora',
    category: 'easter_egg', emoji: '🐸', rarity: 'Common',
    description: 'Common near ponds and streams. Harmless. Part of the freshwater ecosystem.',
    personality: 'Hoppy and harmless. The sound of summer evenings near Blue Lake.',
    biomes: ['freshwater_river'],
    preferredDepth: [0, 2], preferredSeason: ['spring', 'summer'], peakMonth: [6, 7],
    sizeRange: [0.05, 0.15], avgWeight: 0.08, fightStrength: 0, speed: 3,
    baseValue: 0, cookValue: 0, marketDemand: 'none',
    preferredBait: ['none'],
    schools: false, predators: ['blue_heron', 'otter'],
    notes: 'Ambient wildlife. Part of the freshwater world-building. Their croaking at dusk means the ecosystem is healthy.',
  },

  // ═══════════════════════════════════════════════════════════════
  // PLANTS / SEAWEED
  // ═══════════════════════════════════════════════════════════════
  {
    id: 'bull_kelp', name: 'Bull Kelp', scientificName: 'Nereocystis luetkeana',
    category: 'easter_egg', emoji: '🌊', rarity: 'Common',
    description: 'THE iconic Alaska kelp. Can grow 100+ feet. Gas-filled bulb floats on surface. Important habitat.',
    personality: 'The forest of the sea. Without bull kelp, Southeast Alaska is just rocks and rain.',
    biomes: ['kelp_forest', 'sheltered_sound'],
    preferredDepth: [2, 30], preferredSeason: ['spring', 'summer', 'fall'], peakMonth: [7, 8],
    sizeRange: [10, 120], avgWeight: 5, fightStrength: 0, speed: 0,
    baseValue: 2, cookValue: 8, marketDemand: 'moderate',
    preferredBait: ['hands'],
    schools: true, predators: ['sea_urchin'],
    notes: 'Pickled bull kelp bulbs are an Alaska delicacy. The bulb is filled with gas. Kelp forests are critical habitat for rockfish, greenling, and hundreds of species.',
  },
  {
    id: 'rockweed', name: 'Rockweed', scientificName: 'Fucus distichus',
    category: 'easter_egg', emoji: '🌿', rarity: 'Common',
    description: 'Intertidal zone seaweed. Common on rocks. Olive-brown with paired bladders.',
    personality: 'The tide pool regular. Always there when the water goes out.',
    biomes: ['tidal_flats', 'rocky_pinnacles'],
    preferredDepth: [0, 3], preferredSeason: ['year_round'], peakMonth: [5, 6, 7],
    sizeRange: [0.2, 1], avgWeight: 0.3, fightStrength: 0, speed: 0,
    baseValue: 1, cookValue: 3, marketDemand: 'low',
    preferredBait: ['hands'],
    schools: true, predators: ['limpet'],
    notes: 'Common intertidal seaweed. The bladders keep it floating at high tide. Good habitat for small creatures.',
  },
  {
    id: 'sea_lettuce', name: 'Sea Lettuce', scientificName: 'Ulva lactuca',
    category: 'easter_egg', emoji: '🥬', rarity: 'Common',
    description: 'Bright green algae. Edible. Found in sheltered bays and estuaries.',
    personality: 'Green and wavy. Looks like actual lettuce. Because it is.',
    biomes: ['tidal_flats', 'river_estuary', 'sheltered_sound'],
    preferredDepth: [0, 5], preferredSeason: ['spring', 'summer'], peakMonth: [6, 7],
    sizeRange: [0.1, 0.5], avgWeight: 0.1, fightStrength: 0, speed: 0,
    baseValue: 1, cookValue: 4, marketDemand: 'low',
    preferredBait: ['hands'],
    schools: true, predators: [],
    notes: 'Edible green algae. You can actually eat it in salads. High in vitamins. Grows fast in nutrient-rich waters.',
  },
  {
    id: 'eelgrass', name: 'Eelgrass', scientificName: 'Zostera marina',
    category: 'easter_egg', emoji: '🌾', rarity: 'Common',
    description: 'Underwater grass in sheltered bays. Critical fish nursery habitat.',
    personality: 'The nursery. Baby salmon, herring, and crabs all grow up in eelgrass beds.',
    biomes: ['sheltered_sound', 'tidal_flats'],
    preferredDepth: [0, 10], preferredSeason: ['spring', 'summer'], peakMonth: [6, 7, 8],
    sizeRange: [0.5, 3], avgWeight: 0.2, fightStrength: 0, speed: 0,
    baseValue: 0, cookValue: 0, marketDemand: 'none',
    preferredBait: ['none'],
    schools: true, predators: [],
    notes: 'Not edible but ecologically VITAL. Eelgrass beds are the most productive habitat in the ocean. Protect them.',
  },
  {
    id: 'dulse', name: 'Dulse', scientificName: 'Palmaria mollis',
    category: 'easter_egg', emoji: '🔴', rarity: 'Uncommon',
    description: 'Red algae. Edible. Traditional First Nations food. Rich in protein and iron.',
    personality: 'The red gold of the intertidal. Traditional food for thousands of years.',
    biomes: ['tidal_flats', 'rocky_pinnacles'],
    preferredDepth: [0, 5], preferredSeason: ['spring', 'summer'], peakMonth: [5, 6],
    sizeRange: [0.1, 0.5], avgWeight: 0.05, fightStrength: 0, speed: 0,
    baseValue: 3, cookValue: 10, marketDemand: 'moderate',
    preferredBait: ['hands'],
    schools: true, predators: [],
    notes: 'Traditional Tlingit and Haida food. Dried and eaten like jerky. High in protein and iron. A biology lesson in every bite.',
  },
  {
    id: 'beach_asparagus', name: 'Beach Asparagus', scientificName: 'Salicornia virginica',
    category: 'easter_egg', emoji: '🥒', rarity: 'Common',
    description: 'Salty edible plant on beaches. Crispy, salty, delicious raw or pickled.',
    personality: 'Salty and crunchy. The surprise gourmet ingredient of the beach.',
    biomes: ['tidal_flats'],
    preferredDepth: [0, 1], preferredSeason: ['spring', 'summer'], peakMonth: [6, 7],
    sizeRange: [0.1, 0.3], avgWeight: 0.05, fightStrength: 0, speed: 0,
    baseValue: 3, cookValue: 10, marketDemand: 'moderate',
    preferredBait: ['hands'],
    schools: false, predators: [],
    notes: 'Also called "glasswort" or "samphire." Pick the tender tips. Great in salads or quick-pickled. Beach foraging treasure.',
  },
  {
    id: 'fireweed', name: 'Fireweed', scientificName: 'Chamerion angustifolium',
    category: 'easter_egg', emoji: '🌸', rarity: 'Common',
    description: 'The Alaska state flower. Purple spikes everywhere in summer. Honey is legendary.',
    personality: 'The purple banner of Alaska summer. When fireweed blooms to the top, summer is ending.',
    biomes: ['land', 'mountain'],
    preferredDepth: [0, 0], preferredSeason: ['summer', 'fall'], peakMonth: [7, 8],
    sizeRange: [1, 6], avgWeight: 0.1, fightStrength: 0, speed: 0,
    baseValue: 0, cookValue: 5, marketDemand: 'low',
    preferredBait: ['hands'],
    schools: false, predators: ['bear'],
    notes: 'Alaska state flower. Blooms bottom to top — when it reaches the top, locals say "six weeks until winter." Fireweed honey is some of the best in the world.',
  },
];

export default EXPANDED_SPECIES;
