// CraftMind Fishing — Alaska-Authentic Gear Database
// Every piece of gear is something a real Southeast Alaska fisherman would recognize.

// ─── Gear Categories ──────────────────────────────────────────────────

export const HOOKS = {
  circle_hook: {
    name: 'Circle Hook',
    emoji: '🪝',
    category: 'hook',
    description: 'For halibut — prevents gut-hooking. Alaska regulations REQUIRE circle hooks for halibut.',
    tier: 1,
    durability: 60,
    targetSpecies: ['halibut', 'cod', 'rockfish'],
    required: false,
    regulations: { halibut: 'mandatory' }, // must use for halibut
    effectiveness: { halibut: 1.3, cod: 1.0, rockfish: 0.8 },
  },
  j_hook: {
    name: 'J-Hook',
    emoji: '🪝',
    category: 'hook',
    description: 'General purpose hook. Good for salmon trolling, bottom fishing, anything that swims.',
    tier: 1,
    durability: 50,
    targetSpecies: ['salmon', 'rockfish', 'cod'],
    effectiveness: { salmon: 1.2, rockfish: 1.0, cod: 1.0 },
  },
  treble_hook: {
    name: 'Treble Hook',
    emoji: '🪝',
    category: 'hook',
    description: 'Three points — hard to miss. Used for herring, small bait fish.',
    tier: 1,
    durability: 35,
    targetSpecies: ['herring', 'smelt'],
    effectiveness: { herring: 1.4, smelt: 1.3 },
  },
  siwash_hook: {
    name: 'Siwash Hook',
    emoji: '🪝',
    category: 'hook',
    description: 'Strong, open-eye trolling hook. Replaceable on your lure. The workhorse of SE Alaska trolling.',
    tier: 1,
    durability: 55,
    targetSpecies: ['king_salmon', 'coho_salmon', 'pink_salmon'],
    effectiveness: { king_salmon: 1.2, coho_salmon: 1.3, pink_salmon: 1.2 },
  },
  dinglebar_hook: {
    name: 'Dinglebar Hook',
    emoji: '⚓',
    category: 'hook',
    description: '16-32oz heavy jig for lingcod on pinnacles. You POUND the bottom and rip it up. Lingcod can\'t resist.',
    tier: 2,
    durability: 80,
    targetSpecies: ['lingcod', 'yelloweye', 'rockfish'],
    effectiveness: { lingcod: 1.5, yelloweye: 1.3, rockfish: 1.1 },
    fishDamage: 3, // heavy damage per use on big fish
  },
  cod_jig: {
    name: 'Cod Jig',
    emoji: '🪝',
    category: 'hook',
    description: 'Heavy jig for bottom fish. Drop it to the bottom, jig it up. Cod, pollock, whatever\'s down there.',
    tier: 1,
    durability: 65,
    targetSpecies: ['pacific_cod', 'pollock', 'rockfish'],
    effectiveness: { pacific_cod: 1.3, pollock: 1.2, rockfish: 1.0 },
  },
  hoochie: {
    name: 'Hoochie',
    emoji: '🦑',
    category: 'hook',
    description: 'Rubber squid skirt. Behind a flasher, this is THE salmon trolling setup in SE Alaska.',
    tier: 2,
    durability: 40,
    targetSpecies: ['coho_salmon', 'king_salmon', 'pink_salmon', 'chum_salmon'],
    effectiveness: { coho_salmon: 1.4, king_salmon: 1.2, pink_salmon: 1.3, chum_salmon: 1.2 },
  },
  buzz_bomb: {
    name: 'Buzz Bomb',
    emoji: '💣',
    category: 'hook',
    description: 'Metal jig — cast and retrieve. The original "dart and jig." Killer for salmon from shore.',
    tier: 2,
    durability: 55,
    targetSpecies: ['pink_salmon', 'coho_salmon', 'dolly_varden'],
    effectiveness: { pink_salmon: 1.4, coho_salmon: 1.2, dolly_varden: 1.3 },
  },
  zig_zag: {
    name: 'Zig Zag',
    emoji: '⚡',
    category: 'hook',
    description: 'Metal jig similar to a buzz bomb. Erratic action drives salmon crazy. A Sitka staple.',
    tier: 2,
    durability: 55,
    targetSpecies: ['coho_salmon', 'pink_salmon', 'chum_salmon'],
    effectiveness: { coho_salmon: 1.3, pink_salmon: 1.3, chum_salmon: 1.1 },
  },
  crippled_herring: {
    name: 'Crippled Herring',
    emoji: '🐟',
    category: 'hook',
    description: 'Metal jig that drops FAST. Let it flutter down on a slack line — bottom fish smash it.',
    tier: 2,
    durability: 50,
    targetSpecies: ['pacific_cod', 'rockfish', 'lingcod'],
    effectiveness: { pacific_cod: 1.4, rockfish: 1.3, lingcod: 1.2 },
  },
  point_wilson_dart: {
    name: 'Point Wilson Dart',
    emoji: '🎯',
    category: 'hook',
    description: 'Classic PNW salmon jig. Point Wilson, WA — right across the strait. Works everywhere salmon swim.',
    tier: 2,
    durability: 50,
    targetSpecies: ['coho_salmon', 'king_salmon', 'pink_salmon'],
    effectiveness: { coho_salmon: 1.3, king_salmon: 1.1, pink_salmon: 1.2 },
  },
  mooching_rig: {
    name: 'Mooching Rig',
    emoji: '🎣',
    category: 'hook',
    description: 'Cut-plug herring setup. Drift with the current, letting the herring spin. The old-school way.',
    tier: 2,
    durability: 30,
    targetSpecies: ['king_salmon', 'coho_salmon'],
    effectiveness: { king_salmon: 1.4, coho_salmon: 1.3 },
    requiresBait: 'herring',
  },
};

export const LINE = {
  mono_10lb: {
    name: 'Monofilament 10lb',
    emoji: '🧵',
    category: 'line',
    description: 'Light mono for trout and small salmon. Cheap, stretchy, forgiving. Good for kids.',
    tier: 1,
    durability: 70,
    breakStrength: 10,
    stretch: 0.3,
    sensitivity: 0.5,
  },
  mono_20lb: {
    name: 'Monofilament 20lb',
    emoji: '🧵',
    category: 'line',
    description: 'The do-everything line. Coho, rockfish, bottom fish. If you only buy one spool, make it 20lb mono.',
    tier: 1,
    durability: 70,
    breakStrength: 20,
    stretch: 0.25,
    sensitivity: 0.6,
  },
  mono_40lb: {
    name: 'Monofilament 40lb',
    emoji: '🧵',
    category: 'line',
    description: 'Heavy mono for mooching and light halibut. Good shock absorber for big kings.',
    tier: 1,
    durability: 75,
    breakStrength: 40,
    stretch: 0.2,
    sensitivity: 0.6,
  },
  mono_80lb: {
    name: 'Monofilament 80lb',
    emoji: '🧵',
    category: 'line',
    description: 'Heavy mono for halibut leaders. Some guys run 80lb mono mainline — it works.',
    tier: 2,
    durability: 80,
    breakStrength: 80,
    stretch: 0.15,
    sensitivity: 0.7,
  },
  braid_30lb: {
    name: 'Braided Line 30lb',
    emoji: '🧶',
    category: 'line',
    description: 'No-stretch, razor-thin, incredibly sensitive. You feel EVERYTHING. Rockfish and coho love it.',
    tier: 2,
    durability: 90,
    breakStrength: 30,
    stretch: 0.0,
    sensitivity: 1.0,
  },
  braid_50lb: {
    name: 'Braided Line 50lb',
    emoji: '🧶',
    category: 'line',
    description: 'The sweet spot. Strong enough for halibut, thin enough for sensitivity. Sitka go-to.',
    tier: 2,
    durability: 95,
    breakStrength: 50,
    stretch: 0.0,
    sensitivity: 1.0,
  },
  braid_80lb: {
    name: 'Braided Line 80lb',
    emoji: '🧶',
    category: 'line',
    description: 'Heavy braid for serious halibut. No stretch means you set the hook HARD at 300 feet.',
    tier: 2,
    durability: 100,
    breakStrength: 80,
    stretch: 0.0,
    sensitivity: 1.0,
  },
  braid_130lb: {
    name: 'Braided Line 130lb',
    emoji: '🧶',
    category: 'line',
    description: 'Big game braid. Halibut, tuna, anything that wants to kill your gear. The heavy artillery.',
    tier: 3,
    durability: 110,
    breakStrength: 130,
    stretch: 0.0,
    sensitivity: 1.0,
  },
  braid_200lb: {
    name: 'Braided Line 200lb',
    emoji: '🧶',
    category: 'line',
    description: 'Insane strength. For longlining and extreme deep water. Overkill for anything but barn-door halibut.',
    tier: 4,
    durability: 120,
    breakStrength: 200,
    stretch: 0.0,
    sensitivity: 0.9,
  },
  lead_core: {
    name: 'Lead Core Line',
    emoji: '⚙️',
    category: 'line',
    description: 'Sinking line for getting lures deep while trolling. Each color section = 10 yards. Counts your depth.',
    tier: 2,
    durability: 60,
    breakStrength: 30,
    stretch: 0.1,
    sensitivity: 0.4,
    sinkRate: 0.5, // sinks ~5ft per color
  },
  wire_leader_40lb: {
    name: 'Wire Leader 40lb',
    emoji: '⛓️',
    category: 'line',
    description: 'Single-strand wire for sharp teeth. Sharks, lingcod, anything with teeth that bites.',
    tier: 2,
    durability: 80,
    breakStrength: 40,
    stretch: 0.0,
    sensitivity: 0.8,
    toothProof: true,
  },
  wire_leader_80lb: {
    name: 'Wire Leader 80lb',
    emoji: '⛓️',
    category: 'line',
    description: 'Heavy wire leader for big halibut and sharks. Don\'t go halibut fishing without it.',
    tier: 2,
    durability: 85,
    breakStrength: 80,
    stretch: 0.0,
    sensitivity: 0.8,
    toothProof: true,
  },
  wire_leader_100lb: {
    name: 'Wire Leader 100lb',
    emoji: '⛓️',
    category: 'line',
    description: 'Extra-heavy wire. For the big boys. When a 200lb halibut bites, this is what stands between you and a broken line.',
    tier: 3,
    durability: 90,
    breakStrength: 100,
    stretch: 0.0,
    sensitivity: 0.8,
    toothProof: true,
  },
  dacron_30lb: {
    name: 'Dacron 30lb',
    emoji: '🧵',
    category: 'line',
    description: 'Old school, stretchy, forgiving. Your grandpa\'s mooching line. Still works fine.',
    tier: 1,
    durability: 65,
    breakStrength: 30,
    stretch: 0.35,
    sensitivity: 0.4,
  },
};

export const RODS = {
  light_spin_rod: {
    name: 'Light Spin Rod',
    emoji: '🎣',
    category: 'rod',
    description: '6-7 foot, light action. Trout, Dolly Varden, pink salmon, jigging rockfish. The everyday rod.',
    tier: 1,
    durability: 100,
    maxLineWeight: 12,
    maxLureWeight: 0.5,
    targetSpecies: ['trout', 'dolly_varden', 'pink_salmon', 'rockfish'],
    castDistance: 20,
  },
  medium_spin_rod: {
    name: 'Medium Spin Rod',
    emoji: '🎣',
    category: 'rod',
    description: '7-8 foot, medium action. The do-everything rod. Coho, bottom fish, rockfish, halibut if you must.',
    tier: 1,
    durability: 110,
    maxLineWeight: 25,
    maxLureWeight: 2,
    targetSpecies: ['coho_salmon', 'rockfish', 'pacific_cod', 'halibut'],
    castDistance: 25,
  },
  heavy_mooching_rod: {
    name: 'Heavy Mooching Rod',
    emoji: '🎣',
    category: 'rod',
    description: '8-10 foot, long and flexible. For mooching cut-plug herring for king salmon. You drift and wait.',
    tier: 2,
    durability: 120,
    maxLineWeight: 40,
    maxLureWeight: 4,
    targetSpecies: ['king_salmon', 'coho_salmon'],
    castDistance: 15,
  },
  halibut_rod: {
    name: 'Halibut Rod',
    emoji: '🎣',
    category: 'rod',
    description: '5-6 foot, short and stiff, 80-130lb class. Built to winch barn doors off the bottom. No finesse needed.',
    tier: 2,
    durability: 140,
    maxLineWeight: 130,
    maxLureWeight: 16,
    targetSpecies: ['halibut'],
    castDistance: 10,
  },
  dinglebar_rod: {
    name: 'Dinglebar Rod',
    emoji: '🪓',
    category: 'rod',
    description: 'EXTRA heavy, extra short. For pounding 16-32oz jigs on bottom structure. Lingcod dream rod.',
    tier: 3,
    durability: 160,
    maxLineWeight: 130,
    maxLureWeight: 32,
    targetSpecies: ['lingcod', 'yelloweye'],
    castDistance: 8,
  },
  trolling_rod: {
    name: 'Trolling Rod',
    emoji: '🚤',
    category: 'rod',
    description: '7-9 foot, flexible, mounted in a holder. Pulls gear behind the boat all day. Salmon trolling standard.',
    tier: 2,
    durability: 120,
    maxLineWeight: 30,
    maxLureWeight: 3,
    targetSpecies: ['king_salmon', 'coho_salmon', 'pink_salmon', 'chum_salmon'],
    castDistance: 15,
  },
  fly_rod: {
    name: 'Fly Rod',
    emoji: '🪰',
    category: 'rod',
    description: '8-9 foot weight 7-8 for river fishing. Dolly Varden, cutthroat, steelhead, pink salmon.',
    tier: 1,
    durability: 80,
    maxLineWeight: 20,
    maxLureWeight: 0.25,
    targetSpecies: ['dolly_varden', 'cutthroat', 'steelhead', 'pink_salmon'],
    castDistance: 18,
  },
  spear: {
    name: 'Spear',
    emoji: '🔱',
    category: 'rod',
    description: 'Free-dive spearfishing spear. One shot, make it count. For rockfish, lingcod, and greenling.',
    tier: 2,
    durability: 60,
    maxLineWeight: 0,
    targetSpecies: ['rockfish', 'lingcod', 'greenling'],
    castDistance: 5,
  },
};

export const REELS = {
  spinning_reel: {
    name: 'Spinning Reel',
    emoji: '⚙️',
    category: 'reel',
    description: 'The reel everyone starts with. Versatile, easy to use. Good to 20lb line.',
    tier: 1,
    durability: 100,
    maxDrag: 10,
    maxLineWeight: 20,
    lineCapacity: 150,
  },
  level_wind_reel: {
    name: 'Level Wind Reel',
    emoji: '⚙️',
    category: 'reel',
    description: 'Conventional reel for heavy bottom fishing. Level wind lays line evenly. Halibut standard.',
    tier: 2,
    durability: 120,
    maxDrag: 25,
    maxLineWeight: 80,
    lineCapacity: 300,
  },
  shimano_talica: {
    name: 'Shimano Talica',
    emoji: '💎',
    category: 'reel',
    description: 'Two-speed lever drag. Push the button, shift from high to low gear. The reel halibut dreams are made of.',
    tier: 3,
    durability: 150,
    maxDrag: 40,
    maxLineWeight: 130,
    lineCapacity: 500,
    twoSpeed: true,
  },
  avet_hx: {
    name: 'Avet HX',
    emoji: '💎',
    category: 'reel',
    description: 'Lever drag reel. Smaller than a Talica but packs a punch. Great for stand-up halibut fishing.',
    tier: 3,
    durability: 140,
    maxDrag: 30,
    maxLineWeight: 80,
    lineCapacity: 400,
    twoSpeed: true,
  },
  daiwa_sea_line: {
    name: 'Daiwa Sealine',
    emoji: '⚙️',
    category: 'reel',
    description: 'Solid conventional reel. Not fancy, not expensive, but it just works. Workhorse of the charter fleet.',
    tier: 2,
    durability: 130,
    maxDrag: 20,
    maxLineWeight: 60,
    lineCapacity: 350,
  },
  fly_reel: {
    name: 'Fly Reel',
    emoji: '⚙️',
    category: 'reel',
    description: 'Click-and-pawl or disc drag. Holds fly line and backs up the rod when a steelhead runs.',
    tier: 1,
    durability: 80,
    maxDrag: 5,
    maxLineWeight: 20,
    lineCapacity: 100,
  },
  hand_reel: {
    name: 'Hand Reel',
    emoji: '🤲',
    category: 'reel',
    description: 'A simple spool of line and a handle. For pot fishing. Pull it up by hand. Cheap and simple.',
    tier: 1,
    durability: 60,
    maxDrag: 0,
    maxLineWeight: 20,
    lineCapacity: 200,
  },
  electric_reel: {
    name: 'Electric Reel',
    emoji: '🔌',
    category: 'reel',
    description: 'Push a button, it reels for you. For deep water longlining 300+ feet. Expensive but your back will thank you.',
    tier: 3,
    durability: 100,
    maxDrag: 30,
    maxLineWeight: 130,
    lineCapacity: 600,
    electric: true,
  },
};

export const NETS_TRAPS = {
  gill_net: {
    name: 'Gill Net',
    emoji: '🕸️',
    category: 'net',
    description: 'Set net for salmon in the straits and sounds. Soak it overnight, pick fish in the morning.',
    tier: 2,
    durability: 80,
    targetSpecies: ['salmon'],
    soakTime: 28800000, // 8 hours
  },
  purse_seine_net: {
    name: 'Purse Seine Net',
    emoji: '🛥️',
    category: 'net',
    description: 'HUGE net that encircles a school of salmon. Requires a crew and a power skiff to set.',
    tier: 4,
    durability: 200,
    targetSpecies: ['salmon'],
    requiresCrew: 4,
  },
  beach_seine: {
    name: 'Beach Seine',
    emoji: '🏖️',
    category: 'net',
    description: 'Deploy from the beach, sweep a curve, pull it in. Shore-based salmon fishing. Family operation.',
    tier: 2,
    durability: 100,
    targetSpecies: ['pink_salmon', 'chum_salmon', 'dolly_varden'],
  },
  dungeness_pot: {
    name: 'Dungeness Pot',
    emoji: '🦀',
    category: 'trap',
    description: 'Wire pot with 3 entry funnels. Bait with herring or fish carcass. Soak 12-24 hours. The bread and butter.',
    tier: 1,
    durability: 120,
    targetSpecies: ['dungeness_crab'],
    soakTime: 43200000, // 12 hours
  },
  king_crab_pot: {
    name: 'King Crab Pot',
    emoji: '🦀',
    category: 'trap',
    description: '80lb+ steel pot. Requires a pot puller — you\'re NOT hauling this by hand. Bering Sea gear.',
    tier: 4,
    durability: 200,
    targetSpecies: ['king_crab'],
    requiresGear: 'pot_puller',
    soakTime: 86400000, // 24 hours
  },
  tanner_crab_pot: {
    name: 'Tanner Crab Pot',
    emoji: '🦀',
    category: 'trap',
    description: 'Smaller conical pot for Tanner (snow) crab. Similar setup to king pot but lighter.',
    tier: 3,
    durability: 150,
    targetSpecies: ['tanner_crab'],
    soakTime: 64800000, // 18 hours
  },
  shrimp_pot: {
    name: 'Shrimp Pot',
    emoji: '🦐',
    category: 'trap',
    description: 'Small baited pot for spot prawns. Soak overnight near rocky structure. Best bait: cat food or herring.',
    tier: 2,
    durability: 80,
    targetSpecies: ['spot_prawn', 'sidestripe_shrimp'],
    soakTime: 43200000,
  },
  octopus_pot: {
    name: 'Octopus Pot',
    emoji: '🐙',
    category: 'trap',
    description: 'Modified pot with a larger entry. Bait with a crab — the octopus comes in for the crab and stays for the pot.',
    tier: 3,
    durability: 130,
    targetSpecies: ['giant_octopus'],
    soakTime: 86400000,
  },
  trawl_net: {
    name: 'Trawl Net',
    emoji: '🛥️',
    category: 'net',
    description: 'Industrial net dragged behind a boat. Scoops up everything. Controversial — destroys habitat.',
    tier: 4,
    durability: 200,
    targetSpecies: ['*'],
    ecosystemDamage: 0.15,
  },
};

export const BOAT_GEAR = {
  pot_puller: {
    name: 'Pot Puller',
    emoji: '🔧',
    category: 'boat',
    description: 'Hydraulic or electric pot hauler. Essential for king crab pots — pulling 200ft of soaked rope by hand is insanity.',
    tier: 3,
    durability: 180,
  },
  hydraulic_hooker: {
    name: 'Hydraulic Hooker',
    emoji: '🔧',
    category: 'boat',
    description: 'For longline gear. Pulls the groundline with hooks attached. The longliner\'s best friend.',
    tier: 4,
    durability: 200,
  },
  downrigger: {
    name: 'Downrigger',
    emoji: '⬇️',
    category: 'boat',
    description: 'Gets your trolling gear to EXACT depth. Critical for salmon — they suspend at specific depths.',
    tier: 2,
    durability: 130,
    depthRange: 200,
  },
  fish_finder: {
    name: 'Fish Finder',
    emoji: '📡',
    category: 'boat',
    description: 'Sonar unit. Shows fish schools, bottom structure, thermocline. You\'re blind without it.',
    tier: 2,
    durability: 150,
    catchBonus: 0.2,
  },
  gps: {
    name: 'GPS',
    emoji: '📍',
    category: 'boat',
    description: 'Mark waypoints, navigate fishing spots. "Drop me on the numbers" is the Sitka way.',
    tier: 2,
    durability: 200,
    catchBonus: 0.1,
  },
  anchor: {
    name: 'Anchor',
    emoji: '⚓',
    category: 'boat',
    description: 'Hold position in current and wind. Essential for halibut fishing — you need to stay on the spot.',
    tier: 1,
    durability: 200,
  },
  pot_line: {
    name: 'Pot Line',
    emoji: '🪢',
    category: 'boat',
    description: 'Rope for crab/shrimp pots, marked with buoys. 200-400ft for deep water sets.',
    tier: 1,
    durability: 100,
  },
  buoy: {
    name: 'Buoy',
    emoji: '🔴',
    category: 'boat',
    description: 'Marks your pot or longline location. Coast Guard requires them — and other fishermen respect them.',
    tier: 1,
    durability: 90,
  },
  crimp: {
    name: 'Crimp',
    emoji: '🔧',
    category: 'boat',
    description: 'Metal sleeve crimped onto line to attach hooks. The right connection makes or breaks your setup.',
    tier: 1,
    durability: 50,
  },
  snap_swivel: {
    name: 'Snap Swivel',
    emoji: '🔗',
    category: 'boat',
    description: 'Prevents line twist. Snap on your lure, swivel keeps the line straight. Essential for trolling.',
    tier: 1,
    durability: 40,
    twistPrevention: true,
  },
  skirt: {
    name: 'Skirt',
    emoji: '🎀',
    category: 'boat',
    description: 'Rubber/plastic skirt over your hook. Attracts fish, adds action. Change colors until they bite.',
    tier: 1,
    durability: 30,
    catchBonus: 0.1,
  },
};

export const DIVING_GEAR = {
  wetsuit_3mm: {
    name: 'Wetsuit 3mm',
    emoji: '🤿',
    category: 'dive',
    description: 'Thin wetsuit for summer diving. Good to about 55°F water. Southeast Alaska summer temps.',
    tier: 2,
    durability: 80,
    tempRating: 55,
  },
  wetsuit_5mm: {
    name: 'Wetsuit 5mm',
    emoji: '🤿',
    category: 'dive',
    description: 'Standard cold water wetsuit. Good to 48°F. Most Alaska divers live in 5mm.',
    tier: 2,
    durability: 90,
    tempRating: 48,
  },
  wetsuit_7mm: {
    name: 'Wetsuit 7mm',
    emoji: '🤿',
    category: 'dive',
    description: 'Thick wetsuit for cold water. Good to 42°F. Stiff but keeps you alive.',
    tier: 3,
    durability: 100,
    tempRating: 42,
  },
  dry_suit: {
    name: 'Dry Suit',
    emoji: '🤿',
    category: 'dive',
    description: 'Stays DRY. Expensive, requires maintenance, but you can dive in 38°F water for hours. Sea cucumber divers use these.',
    tier: 4,
    durability: 70,
    tempRating: 35,
  },
  mask: {
    name: 'Dive Mask',
    emoji: '🥽',
    category: 'dive',
    description: 'Tempered glass, low volume. Clear vision underwater. Don\'t cheap out — foggy mask ruins the dive.',
    tier: 1,
    durability: 60,
  },
  fins: {
    name: 'Dive Fins',
    emoji: '🦶',
    category: 'dive',
    description: 'Open heel with booties for cold water. Long fins for free diving, shorter for SCUBA.',
    tier: 1,
    durability: 70,
  },
  dive_computer: {
    name: 'Dive Computer',
    emoji: '⌚',
    category: 'dive',
    description: 'Tracks depth, time, decompression. Without it, you\'re guessing. The most important safety device.',
    tier: 3,
    durability: 120,
    catchBonus: 0.15,
  },
  regulator: {
    name: 'Regulator',
    emoji: '🌬️',
    category: 'dive',
    description: 'SCUBA breathing apparatus. Reduces tank pressure to breathable air. Your lifeline underwater.',
    tier: 3,
    durability: 100,
  },
  tank_al80: {
    name: 'Aluminum 80 Tank',
    emoji: '🫙',
    category: 'dive',
    description: 'Standard aluminum 80 cubic foot tank. About 60 minutes of air at recreational depths.',
    tier: 2,
    durability: 150,
    airCapacity: 80,
  },
  tank_steel100: {
    name: 'Steel 100 Tank',
    emoji: '🫙',
    category: 'dive',
    description: 'More air, less buoyancy shift. Serious divers prefer steel. Good for deeper or longer dives.',
    tier: 3,
    durability: 160,
    airCapacity: 100,
  },
  bcd: {
    name: 'BCD',
    emoji: '🦺',
    category: 'dive',
    description: 'Buoyancy Control Device. Inflate to go up, deflate to go down. The jacket that keeps you safe.',
    tier: 3,
    durability: 110,
  },
  dive_light: {
    name: 'Dive Light',
    emoji: '🔦',
    category: 'dive',
    description: 'Underwater flashlight. Night dives, deep dives, looking in crevices. Reveals the hidden world.',
    tier: 2,
    durability: 70,
    catchBonus: 0.1,
  },
  dive_knife: {
    name: 'Dive Knife',
    emoji: '🔪',
    category: 'dive',
    description: 'Tool and safety device. Cut line, pry shells, signal to your buddy. Strapped to your leg.',
    tier: 1,
    durability: 90,
  },
  catch_bag: {
    name: 'Catch Bag',
    emoji: '👜',
    category: 'dive',
    description: 'Mesh bag for holding your harvest. Clip it to your BC. Don\'t overload it or you\'ll lose buoyancy.',
    tier: 1,
    durability: 50,
    capacity: 10,
  },
  abalone_iron: {
    name: 'Abalone Iron',
    emoji: '🔩',
    category: 'dive',
    description: 'Flat bar for prying abalone off rocks. Not a knife — the regs are specific. Don\'t use a knife on abalone.',
    tier: 2,
    durability: 80,
    targetSpecies: ['abalone'],
  },
};

export const MISC = {
  harpoon: {
    name: 'Harpoon',
    emoji: '🔱',
    category: 'specialty',
    description: 'For landing large halibut alongside the boat. Sport fishing style. A flying gaff on a rope.',
    tier: 3,
    durability: 70,
    targetSpecies: ['halibut'],
  },
  gaff: {
    name: 'Gaff',
    emoji: '🪝',
    category: 'specialty',
    description: 'Large hook on a handle. For landing big fish you can\'t lift by the line. Stick \'em and swing.',
    tier: 2,
    durability: 80,
  },
  bang_stick: {
    name: 'Bang Stick',
    emoji: '💥',
    category: 'specialty',
    description: 'Powerhead on a pole. For dispatching sharks or dangerous fish. Don\'t ask where to get one.',
    tier: 5,
    durability: 30,
    easterEgg: true,
    targetSpecies: ['shark', 'halibut'],
  },
  fillet_knife: {
    name: 'Fillet Knife',
    emoji: '🔪',
    category: 'specialty',
    description: 'Flexible, sharp, thin blade. Clean your fish on the boat. Fresh fillets = better quality = better price.',
    tier: 1,
    durability: 60,
    qualityBonus: 0.15,
  },
  slime_bag: {
    name: 'Slime Bag',
    emoji: '👜',
    category: 'specialty',
    description: 'Wet bag that keeps fish slime intact. Fish stay fresher, last longer. Charter boats use these.',
    tier: 2,
    durability: 40,
    qualityBonus: 0.2,
  },
  bait_cooler: {
    name: 'Bait Cooler',
    emoji: '🧊',
    category: 'specialty',
    description: 'Keeps bait fresh and cold. Fresh herring outfishes frozen herring 2-to-1.',
    tier: 1,
    durability: 70,
    baitEffectiveness: 0.3,
  },
  flasher: {
    name: 'Flasher',
    emoji: '✨',
    category: 'specialty',
    description: 'Rotating metal flasher for salmon trolling. The spin and flash drives salmon nuts. Run your hoochie 36" behind it.',
    tier: 2,
    durability: 80,
    catchBonus: 0.25,
    targetSpecies: ['salmon'],
  },
  diver_plate: {
    name: 'Diver Plane',
    emoji: '🛩️',
    category: 'specialty',
    description: 'Attractor that dives when trolled. Alternative to downrigger for getting lures deep.',
    tier: 2,
    durability: 70,
    catchBonus: 0.15,
  },
  herring_rigs: {
    name: 'Herring Rigs',
    emoji: '🐟',
    category: 'specialty',
    description: 'Pre-rigged herring behind a flasher. For mooching or trolling. The Sitka charter standard.',
    tier: 2,
    durability: 20,
    requiresBait: 'herring',
    catchBonus: 0.2,
  },
  bucktail_jig: {
    name: 'Bucktail Jig',
    emoji: '🪶',
    category: 'specialty',
    description: 'Hair jig tied with deer tail. For bottom fish and lingcod. The old-timer\'s secret weapon.',
    tier: 2,
    durability: 50,
    targetSpecies: ['rockfish', 'lingcod', 'greenling'],
    effectiveness: { rockfish: 1.3, lingcod: 1.2, greenling: 1.4 },
  },
};

// ─── All Gear Lookup ──────────────────────────────────────────────────

export const ALL_GEAR = {
  ...HOOKS,
  ...LINE,
  ...RODS,
  ...REELS,
  ...NETS_TRAPS,
  ...BOAT_GEAR,
  ...DIVING_GEAR,
  ...MISC,
};

/** Get gear by ID */
export function getGear(id) {
  return ALL_GEAR[id] ?? null;
}

/** Get gear by category */
export function getGearByCategory(category) {
  return Object.entries(ALL_GEAR).filter(([, g]) => g.category === category);
}

/** Get gear by tier */
export function getGearByTier(tier) {
  return Object.entries(ALL_GEAR).filter(([, g]) => g.tier === tier);
}

/** Get species recommendations */
export function getRecommendedGear(speciesId) {
  const matches = [];
  for (const [id, gear] of Object.entries(ALL_GEAR)) {
    if (gear.targetSpecies?.includes(speciesId) || gear.targetSpecies?.includes('*')) {
      const eff = gear.effectiveness?.[speciesId] ?? 1.0;
      matches.push({ id, ...gear, matchScore: eff });
    }
  }
  return matches.sort((a, b) => b.matchScore - a.matchScore);
}

export default ALL_GEAR;
